const projects = [
  {name:'OrderFlow', apis:10, number:'01', kind:'COMMERCE · API INTEGRATION & PERFORMANCE', flow:['Reserve','Order','Cancel'], description:'A stateful commerce API testing project. Follow inventory reservations through order creation and cancellation, with checks for stock limits, ownership and duplicate requests.', tags:['Java','Cucumber','REST Assured','JMeter','Grafana'], slug:'orderflow-api-quality'},
  {name:'LedgerGuard', apis:9, number:'02', kind:'PAYMENTS · API INTEGRATION & PERFORMANCE', flow:['Fund','Transfer','Reverse'], description:'A payment workflow testing project. Exercise account balances, atomic transfers and reversals, including insufficient funds, access control and idempotency conflicts.', tags:['Java','Cucumber','REST Assured','JMeter','Grafana'], slug:'ledgerguard-api-quality'},
];
export default function Home(){return <div className="wrap">
<header className="site-header">
  <a className="brand" href="#" aria-label="Ali Waris — home">
    <span className="brand-mark" aria-hidden="true">AW</span>
    <span className="brand-copy"><span className="brand-name">Ali Waris</span><span className="brand-role">Test Automation Engineer</span></span>
  </a>
  <nav className="header-nav" aria-label="Main navigation">
    <a className="nav-link" href="#projects">Selected work</a>
    <a className="nav-link" href="#about">About</a>
    <a className="nav-link github-link" href="https://github.com/aliwaris-labs" target="_blank" rel="noreferrer">GitHub <span aria-hidden="true">↗</span></a>
  </nav>
</header>
<main><section className="hero"><div><div className="eyebrow">Test Automation Engineer</div><h1>Confidence in<br/>every <em>request.</em></h1><p className="intro">I’m Ali Waris. I build API test suites that explore the happy path, challenge the edge cases, and put performance under pressure.</p><div className="actions"><a className="primary" href="#projects">Explore my projects ↓</a><a className="text-link" href="https://github.com/aliwaris-labs" target="_blank" rel="noreferrer">GitHub profile ↗</a></div></div>
<div className="terminal" aria-label="Example of the testing approach"><div className="terminal-head"><span className="dots">● ● ●</span><span>quality.feature</span></div><div className="terminal-body"><div className="comment"># Test the promise. And the limits.</div><br/><div><span className="green">Feature:</span> Confidence in an API</div><br/><div><span className="blue">Given</span> a realistic business workflow</div><div><span className="blue">When</span> success and failure are tested</div><div><span className="blue">Then</span> every response has a contract</div><div><span className="blue">And</span> latency is measured under load</div><br/><div className="green">→ Functional + performance coverage</div></div><div className="terminal-foot">Behavior first. Evidence always.</div></div></section>
<div className="techline"><span>TOOLKIT /</span>{['Java','Cucumber','REST Assured','Apache JMeter','Grafana','GitHub Actions'].map(t=><span key={t}>{t}</span>)}</div>
<section className="section" id="projects"><div className="section-title"><div><span className="small">01 / SELECTED WORK</span><h2>Quality, put into practice.</h2></div><span className="small">Two domains. One testing discipline.</span></div><div className="projects">{projects.map(p=><article className="project" key={p.name}><div className="project-top"><span className="project-no">PROJECT / {p.number}</span><div className="flow">{p.flow.map((f,i)=><span key={f}>{f}{i<2?' →':''}</span>)}</div><span className="project-top-label">{p.kind}</span></div><div className="project-content"><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-bottom"><span>{p.apis} APIs · 22 scenarios</span><a href={`https://github.com/aliwaris-labs/${p.slug}`} target="_blank" rel="noreferrer">View repository ↗</a></div></div></article>)}</div></section>
<section className="section about" id="about"><div><span className="small">02 / APPROACH</span><h2>Beyond a<br/>200 OK.</h2></div><div><p>Good tests explain how a system should behave—even when the inputs, timing or state are wrong. These projects bring business-readable scenarios and measurable performance into the same workflow.</p><div className="principles"><div><h3>Test the whole journey</h3><p>Connected requests, meaningful assertions and isolated test data.</p></div><div><h3>Make performance visible</h3><p>JMeter load profiles with response time, throughput and error metrics in Grafana.</p></div></div></div></section></main><footer><span>Ali Waris · Test Automation Engineer</span><a href="https://github.com/aliwaris-labs" target="_blank" rel="noreferrer">Find me on GitHub ↗</a></footer></div>}
